export {
  ATTRIBUTE_TYPES,
  DAMAGE_TYPE_GROUPS,
  DEFAULT_CONDITIONS,
  DEFAULT_CUSTOM_HANDLERS,
  DEFAULT_DAMAGE_TYPES,
  DEFAULT_MAGIC_EFFECTS,
  DEFAULT_MECHANICS_REGISTRY,
  DEFAULT_SAVE_TYPES,
  DEFAULT_STATS,
  EFFECT_TYPES,
  findDamageTypeEntry,
  findDamageTypeGroup,
  findRegistryEntry,
  formatDamageTypeLabel,
  migrateLegacyDamageTypeId,
  RESISTANCE_ROLES,
  resolveDamageTypeTab,
  validateDamageTypeId,
  validateRegistryId,
  type DamageTypeGroup,
  type MechanicsRegistry,
  type RegistryEntry,
} from './registry.js'

export {
  ATTRIBUTE_BINDING_KIND_LABELS,
  createEmptyBinding,
  DAMAGE_STACKING_RULE_LABELS,
  DAMAGE_STACKING_RULES,
  defaultBindingForKind,
  type DamageStackingRule,
  formatAttributeBinding,
  isMechanicBinding,
  normalizeAttributeBinding,
  normalizeAttributeKey,
  slugifyAttributeKey,
  STACKING_RULE_LABELS,
  VALUE_KIND_LABELS,
  type AttributeBinding,
  type AttributeBindingKind,
  type StackingRule,
  type ValueKind,
} from './bindings.js'

export {
  applyEffectTypeConstraints,
  createEmptyMechanic,
  deriveMechanicKey,
  formatMechanicComposition,
  getMechanicBlocks,
  isActiveMechanic,
  mechanicFromLegacyBinding,
  migrateEffectTypeId,
  normalizeMechanicComposition,
  resolveCompositionToBinding,
  type MechanicBlock,
  type MechanicComposition,
} from './composition.js'

export {
  compileCombatStats,
  createEmptyCompiledCombatStats,
  formatCompiledCombatStats,
  resolveDefinitionBinding,
  stackValuesByRule,
  toEngineScalar,
  type AttributeDefinitionLike,
  type CompiledCombatStats,
  type EngineScalar,
} from './compile.js'
